@startuml Editor


class BaseEditorComponent {
    .. <size:10>@Component</size> ..
    +headingText: string
    +editorId: string
    +displayImageChanged: EventEmitter<any>
    +canvasClick: EventEmitter<any>
    +editorKeydown: EventEmitter<any>
    +editorExpanded: EventEmitter<any>
    +isCollapsed: boolean
    #isCanvasLoading: boolean
    #panzoomInstance: PanZoom
    __
    +setDisplayImage(image: any): void
    +setIsCollapsed(isCollapsed: boolean): void
    +setIsCanvasLoading(isLoading: boolean): void
    #handleKeydown(event: KeyboardEvent): void
    #handleKeyup(event: KeyboardEvent): void
    #handleCanvasClick(event: PointerEvent): void
    #onCollapsePressed(): void
    -createPanzoomInstance(): void
    -{static} globalPanzoomInstances: PanZoom[]
    -{static} isChangingTransforms: boolean
    -{static} globalTransform: Transform
    +{static} resetGlobalTransform(): void
    -{static} setGlobalPanzoomTransform(t: Transform): void
}
abstract class AbstractEditor {
    +displayImageChanged: EventEmitter<any>
    +editorExpanded: EventEmitter<any>
    #baseEditor: BaseEditorComponent
    -WAIT_BEFORE_PROCESSING_MS: number
    +setDisplayImage(image: any): void
    +getDisplayImage(): any
    +setInputImage(image: any): void
    +getInputImage(): any
    +setIsCollapsed(isCollapsed: boolean): void
    +isCollapsed(): boolean
    +setProperty(propertyName: string, value: T): void
    #{abstract} processImage(): void
    #scheduleProcessImage(): void
    #updateDisplayImage(): void
    #onNewInputImage(): void
    #handlePropertyChanged(): void
    #changePropertyAction(propertyName: string, newValue: T): ReversibleAction<T>
}
class Editor1 {
    .. <size:10>@Component</size> ..
}
class Editor2 {
    .. <size:10>@Component</size> ..
}
class Editor3 {
    .. <size:10>@Component</size> ..
}
class ImageDownloader {
    .. <size:10>@Component</size> ..
}


AbstractEditor "1" o-r-  BaseEditorComponent
    
Editor1 .u.|> AbstractEditor
Editor2 .u.|> AbstractEditor
Editor3 .u.|> AbstractEditor
ImageDownloader .u.|> AbstractEditor


@enduml