@startuml Tplant
class ImageUploader {
    #acceptedImageTypes: string[]
    #fileName: string
    #fileUrl: string
    -IMAGE_LOAD_TIMEOUT_MS: 2000
    -MAX_IMAGE_SIDELENGTH_PX: 2500
    -TIMEOUT_WARNING_MESSAGE: "Image loading timed out. Your file may be too large or corrupted."
    -INVALID_FORMAT_WARNING_MESSAGE: "Please upload a valid image format (JPEG, JPG or PNG)."
    -SIZE_WARNING_MESSAGE: string
    #loadTimeoutId: number | undefined
    -originalImageSize: any
    +uploadedImage: any
    #isWarningVisible: boolean
    #warningMessage: string
    #isNewUploadWarningVisible: boolean
    -cdr: ChangeDetectorRef
    +getOriginalImageSize(): any
    +isFilePresent(): boolean
    +isImageLoading(): boolean
    #onDragOver(event: DragEvent): void
    #onFileDrop(event: DragEvent): void
    #onFileUpload(event: Event): void
    #showWarning(message: string): void
    #closeWarning(): void
    #showNewUploadWarning(): void
    #hideNewUploadWarning(): void
    #getNewSize(cvImage: any): any
    -handleUploadedFile(file: File): void
    -startImageLoading(url: string): HTMLImageElement
}
class BaseEditorComponent {
    #panzoomInstance: PanZoom
    #isCanvasLoading: boolean
    +canvasRef: ElementRef<HTMLCanvasElement>
    -canvasContainerRef: ElementRef<HTMLDivElement>
    -collapseToggleRef: ElementRef<HTMLAnchorElement>
    +headingText: string
    +editorId: string
    +displayImageChanged: any
    +canvasClick: any
    +editorKeydown: any
    +editorExpanded: any
    +isCollapsed: boolean
    -cdr: ChangeDetectorRef
    +setDisplayImage(image: any): void
    +setIsCollapsed(isCollapsed: boolean): void
    +setIsCanvasLoading(isLoading: boolean): void
    #resetGlobalTransform(): void
    #handleKeydown(event: KeyboardEvent): void
    #handleKeyup(event: KeyboardEvent): void
    #handleCanvasClick(event: PointerEvent): void
    #onCollapsePressed(): void
    -createPanzoomInstance(): void
    -{static} globalPanzoomInstances: PanZoom[]
    -{static} isChangingTransforms: boolean
    -{static} globalTransform: Transform
    +{static} resetGlobalTransform(): void
    -{static} setGlobalPanzoomTransform(t: Transform): void
}
interface ReversibleActionType<T> {
    +dataStorage?: T | undefined
    +apply(data?: T | undefined): void
    +reverse(data?: T | undefined): void
}
abstract class ReversibleAction<T> implements ReversibleActionType {
    +dataStorage: T
    +{abstract} apply(): void
    +{abstract} reverse(): void
    +{static} of(template: ReversibleActionType<T>): ReversibleAction<T>
    -{static} from(args: ReversibleActionType<T>): ReversibleAction<T>
}
class ChangeValueAction<T> extends ReversibleAction {
    -editor: AbstractEditor
    -propertyName: string
    -originalValue: T
    -newValue: T
    +apply(): void
    +reverse(): void
    +{static} for(editor: AbstractEditor, propertyName: string, newValue: T): ChangeValueAction<T>
}
abstract class AbstractEditor {
    #baseEditor: BaseEditorComponent | undefined
    +displayImageChanged: any
    +editorExpanded: any
    -_displayImage: any
    -_inputImage: any
    -pendingProcessTimeoutId: number | null
    -WAIT_BEFORE_PROCESSING_MS: 100
    +setDisplayImage(image: any): void
    +setDisplayImageWithoutUpdate(image: any): void
    +getDisplayImage(): any
    +setInputImage(image: any): void
    +getInputImage(): any
    +setIsCollapsed(isCollapsed: boolean): void
    +isCollapsed(): boolean
    +setProperty(propertyName: string, value: T): void
    #updateDisplayImage(): void
    #updateDisplayImageWithoutEvent(): void
    #onNewInputImage(): void
    #{abstract} processImage(): void
    #handlePropertyChanged(): void
    #changePropertyAction(propertyName: string, newValue: T): ReversibleAction<T>
    #scheduleProcessImage(): void
    #emitEditorExpanded(): void
}
enum ImageStyleEnum {
    BINARY
    CLASSIC
    VINTAGE
}
class Grad {
    +x: number
    +y: number
    +z: number
    +dot2(x: number, y: number): number
    +dot3(x: number, y: number, z: number): number
}
class Perlin {
    +permutationTable: number[]
    +grad3: Grad[]
    +perm: number[]
    +gradP: Grad[]
    +F2: number
    +G2: number
    +F3: number
    +G3: number
    +simplex2(xin: number, yin: number): number
    +simplex3(xin: number, yin: number, zin: number): number
    -fade(t: number): number
    -lerp(a: number, b: number, t: number): number
    +perlin2(x: number, y: number): number
    +perlin3(x: number, y: number, z: number): number
}
class CvUtils {
    +{static} findContours(image: any): any
    +{static} convertToGrayscale(image: any): any
    +{static} convertToFloat(image: any): any
}
abstract class ImageStyle {
    +{abstract} apply(image: any): any
    +{abstract} drawWithNewSeeds(): any
    +{static} seed: number
    +{static} noise: Perlin
    +{static} noise2: Perlin
    #{static} smallerNoiseMat: any
    #{static} biggerNoiseMat: any
    #{static} contours: any
    #{static} lastInputImage: any
    #{static} rows: number
    #{static} cols: number
    -{static} NOISE_MAT_GENERATION_SIZE: number
    +{static} setInputImage(inputImage: any): void
    +{static} getSeed(): number
    +{static} setSeed(seed: number): void
    +{static} setBiggerNoiseMat(mat: any): void
    +{static} setSmallerNoiseMat(mat: any): void
    +{static} getSmallerNoiseMat(): any
    +{static} getBiggerNoiseMat(): any
    #{static} findContours(): any
    -{static} getBiggerNoiseAt(x: number, y: number): number
    -{static} getSmallerNoiseAt(x: number, y: number): number
    -{static} generateNewNoiseMats(): void
    -{static} scaleAndCropNoiseMats(): void
    -{static} isNoiseMatsValid(): boolean
}
class BinaryStyle extends ImageStyle {
    +apply(image: any): any
    +drawWithNewSeeds(): any
}
class Colors {
    +{static} WHITE: any
    +{static} BLACK: any
    +{static} RED: any
}
+rgb(r: number, g: number, b: number): any
class ClassicStyle extends ImageStyle {
    +LAND_COLOR: any
    +SEA_DEPTH_0: any
    +SEA_DEPTH_1: any
    +SEA_DEPTH_2: any
    +SEA_DEPTH_3: any
    +SEA_DEPTH_4: any
    +FLOAT_WHITE: any
    -thresholds: number[]
    -blurredInputImage: any
    -blurredInputImageFloat: any
    +apply(image: any): any
    +drawWithNewSeeds(): any
    -createOutputImage(): any
    -applyThresholds(image: any): any
    -calculateSeaDepth(): any
}
class VintageStyle extends ImageStyle {
    +AGING_STRENGTH_0: any
    +AGING_STRENGTH_1: any
    +AGING_STRENGTH_2: any
    +AGING_STRENGTH_3: any
    +AGING_STRENGTH_4: any
    +thresholds: number[]
    +apply(image: any): any
    +drawWithNewSeeds(): any
    +applyThresholds(image: any): any
}
class ImageStyleManager {
    -binaryStyle: BinaryStyle
    -vintageStyle: VintageStyle
    -classicStyle: ClassicStyle
    -activeStyle: ImageStyle
    -inputImage: any
    +apply(): any
    +setActive(style: ImageStyleEnum): void
    +setInputImage(image: any): void
    +setSeedAndGetImage(seed: number): any
    -getStyle(style: ImageStyleEnum): ImageStyle
}
class ImageDownloader extends AbstractEditor {
    #imageStyleSelected: ImageStyleEnum
    -styleManager: ImageStyleManager
    +editorExpanded: any
    +baseEditor: BaseEditorComponent
    #downloadFormat: string
    #onNewInputImage(): void
    +processImage(): void
    -applyStyleChanges(): void
    #resetRandomSeeds(): void
    #downloadImage(): Promise<void>
    #loadNoiseMat($event: Event): void
    -convertMatToBlob(mat: any): Promise<Blob>
    -getDownloadName(): string
}
class Slider {
    +min: number
    +max: number
    +step: number
    +id: string
    -actualValue: number
    #previewValue: number
    +value: number
    +value: number
    +valueChange: any
    +onInput(newValue: string): void
    +onChange(): void
    +{static} count: number
}
class Editor1 extends AbstractEditor {
    #sampleSize: number
    #shiftThreshold: number
    #dilationIters: number
    #erosionIters: number
    #isDilationFirst: boolean
    #isResultInverted: boolean
    #isChangeIgnorable: boolean
    -grayScaleInputImage: any
    +displayImageChanged: any
    +editorExpanded: any
    +baseEditor: BaseEditorComponent
    +processImage(): void
    +onNewInputImage(): void
    -adaptiveThreshold(dst: any): void
    -dilateAndErode(dst: any): void
    #toggleIsDilationFirst(): void
    +handlePropertyChanged(): void
}
class Editor3 extends AbstractEditor {
    #coastlineSmoothness: number
    +displayImageChanged: any
    +editorExpanded: any
    +baseEditor: BaseEditorComponent
    +processImage(): void
    #onNewInputImage(): void
    -blurCoastlines(): void
}
class Editor2 extends AbstractEditor {
    #minContourArea: number
    -contours: any
    -contourMap: any
    -selectedContours: Set<number>
    -CONTOUR_CLICK_RADIUS: 9
    +displayImageChanged: any
    +editorExpanded: any
    +baseEditor: BaseEditorComponent
    +processImage(): void
    #handleCanvasClick(event: PointerEvent): void
    #handleKeydown(event: KeyboardEvent): void
    #deleteSelectedContours(): ReversibleAction<deleteContourDataStorage>
    #keepSelectedOnly(): ReversibleAction<any>
    #dropSelection(): void
    -createContourImage(): void
    -createContourMap(): void
    -getClickedContour(clickX: number, clickY: number): number
    -findContourClosestToClick(clickX: number, clickY: number): number
    -deleteContoursAtIndices(indices: number[]): void
    -redrawContours(inds: number[], color: any): void
    -redrawContoursWithoutEvent(inds: number[], color: any): void
    -drawContoursAboveMinArea(image: any, colorFunction: (index: number) => any): void
}
interface deleteContourDataStorage {
    +editor: Editor2
    +deletedIndices: number[]
    +deletedContours: any[]
}
class Project {
    -actionHistory: ReversibleAction<any>[]
    -undoneActions: ReversibleAction<any>[]
    #displayEditors: boolean
    +imageUploader: ImageUploader
    +editor1: Editor1
    +editor2: Editor2
    +editor3: Editor3
    +imageDownloader: ImageDownloader
    +undo(): void
    +redo(): void
    +registerAction(action: ReversibleAction<any>): void
    +getOriginalImageSize(): any
    #keyboardEventHandler(event: KeyboardEvent): void
    #onImageUploaded(image: any): void
    #propagateImageChangeFrom(editorIndex: number): void
    #onEditorExpanded(expandedEditorIndex: number): void
    -isAnyEditorExpandedAfter(editorIndex: number): boolean
    -getEditors(): AbstractEditor[]
}
class App
@enduml