@startuml Adaptive Threshold

left to right direction

package "Bináris kép létrehozása"{
    usecase (P1) as "Sample méretének\nbeállítása"
    usecase (P2) as "Threshold érték korrigálása"
    usecase (P3) as "Eredmény invertálása"
    usecase (P4) as "Tágítás & erodálás\nismétlésszámának beállítása"
    usecase (P5) as "Tágítás & erodálás\nsorrendjének felcserélése"
}

actor :Felhasználó: as User1


User1 --> (P1)
User1 --> (P2)
User1 --> (P3)
User1 --> (P4)
User1 --> (P5)

@enduml