@startuml SelectContours

left to right direction

package "Select Contours"{
    usecase (F1) as "Körvonalak kijelölése"
    usecase (F2) as "Kijelölt körvonalak törlése"
    usecase (F3) as "Csak kijelölt körvonalak megtartása"

}

actor :Felhasználó: as User2

User2 --> (F1)
User2 --> (F2)
User2 --> (F3)

@enduml